name: Publish

on:
  release:
    types: [published]

jobs:
  modrinth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: quick-info-panel-${{ github.event.release.tag_name }}.jar

      # Read the JSON file and save it to a variable
      - name: Load game versions
        id: load-versions
        uses: andstor/file-reader-action@v1
        with:
            path: "versions.json"

      - uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ vars.MODRINTH_ID }}
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: fabric
          game-versions: ${{ steps.load-versions.outputs.contents }}
          files: quick-info-panel-${{ github.event.release.tag_name }}.jar